### ISSUE TITLE
请问每个服务都提供一个WEB层是出于什么样的设计

### ISSUE THREAD

**Issue by z-2x** [micro-in-cn/micro-tutorials#1]
每个服务都有WEB层会不会冗余？提供的WEB层是给外界调用还是服务间通信用的？我认为"WEB层"应该在API处统一暴露给外界来提供接口，服务间通过rpc来通信。

**Comment by printfcoder** [comment]
@z-2x 你好，你的理解是对的，web层直面API对外暴露接口。每个子系统的web并不会互相调用。从我的工作经验上来看，统一的或各自独立的web层都有其意义，统一好管理，分散好发布、易迭代、方便定制。没有一个统一的答案，示具体情况决定，能分散就能统一，这里也是为了有更好更全一些的示例。

谢谢你的疑问，我会在文档里稍加说明，以便读者理解。

**Comment by printfcoder** [comment]
我们可以写两版本接口，/v1分散，/v2集中。觉得如何？

**Comment by z-2x** [comment]
@printfcoder 感谢解惑，，哈哈。两个版本没必要。很好的教程。期待中。。

**Comment by printfcoder** [comment]
@z-2x thx
